const TransactionData = [
  {
    img: "../imgs/users/avatar-1.jpg",
    Id: 1234,
    Name: "Walter Jones",
    Date: "02 Nov, 2022",
    Amount: 1,
    Price: 1234,
    Quantity: 1,
    Status: "Confirm",
  },
  {
    img: "../imgs/users/avatar-2.jpg",
    Id: 1235,
    Name: "Eric Rider",
    Date: "02 Nov, 2022",
    Amount: 1,
    Price: 1512,
    Quantity: 2,
    Status: "Confirm",
  },
  {
    img: "../imgs/users/avatar-3.jpg",
    Id: 1236,
    Name: "Kenneth Jackson",
    Date: "02 Nov, 2022",
    Amount: 1,
    Price: 1571,
    Quantity: 1,
    Status: "Cancel",
  },
  {
    img: "../imgs/users/avatar-4.jpg",
    Id: 1237,
    Name: "Ronnie Spiller",
    Date: "02 Nov, 2022",
    Amount: 1,
    Price: 778,
    Quantity: 2,
    Status: "Cancel",
  },
  {
    img: "../imgs/users/avatar-5.jpg",
    Id: 1238,
    Name: "David willey",
    Date: "02 Nov, 2022",
    Amount: 1,
    Price: 229,
    Quantity: 3,
    Status: "Pending",
  },
];

export default TransactionData;
